# input defines from where the logstash will be receiving data from
# after receiving logs, it parses the logs into json
input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

# output defines the target to which the data will be sent
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "spring-logs-%{+YYYY.MM.dd}"
  }
}
